$ export CHRO_DEBUG=1
  $ timeout 120 Chro -no-over-approx -bound 0 -dsimpl -flat 0 -bmax 11 issue92mini.smt2  | sed 's/[[:space:]]*$//'
  (assert (exists (z)
          (and
            (exists (y) (and
                          (= (+ (* (- 1) y) pow2(eee1) )  0)
                          (<= y  1184)
                          )
            (= (+ eee1 (* (- 1) u0) (* (- 1) z) )  0)
            (<= (* (- 1) u0)  0)
            (<= (* (- 1) z)  -5)
            (<= (* (- 1) pow2(u0))  -37)
            )
  )
  (assert (<= (+ eee1 (* (- 1) pow2(eee1)) )  -1) )
  (assert (<= (+ (* (- 1) eee1) pow2(u0) )  0) )
  (assert (<= (+ u0 (* (- 1) pow2(u0)) )  -1) )
  
  (assert (<= (+ (* (- 1) pow2(eee1)) pow2(u0) )  0) )
  (assert (<= (+ eee1 (* (- 1) pow2(u0)) )  0) )
  (assert (<= (+ (* (- 1) eee1) u0 )  0) )
  
  (assert (exists (y)
          (and
            (= (+ eee2 (* (- 1) u1) (* (- 1) z) )  0)
            (= (+ (* (- 1) y) (* 2 pow2(eee2)) pow2(z) )  0)
            (<= y  1184)
            (<= (* (- 1) u1)  0)
            (<= (* (- 1) z)  -5)
            (<= (* (- 2) pow2(u1))  -36)
            )
  )
  (assert (<= (+ eee2 (* (- 1) pow2(eee2)) )  -1) )
  (assert (<= (+ (* (- 1) eee2) pow2(u1) )  0) )
  (assert (<= (+ u1 (* (- 1) pow2(u1)) )  -1) )
  (assert (<= (+ (* (- 1) u1) pow2(z) )  0) )
  (assert (<= (+ z (* (- 1) pow2(z)) )  -1) )
  
  (assert (<= (+ eee2 (* (- 1) pow2(eee2)) )  -1) )
  (assert (<= (+ (* (- 1) eee2) pow2(u1) )  0) )
  (assert (<= (+ (* (- 1) pow2(u1)) pow2(z) )  0) )
  (assert (<= (+ u1 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) u1) z )  0) )
  
  (assert (<= (+ eee2 (* (- 1) pow2(eee2)) )  -1) )
  (assert (<= (+ (* (- 1) eee2) pow2(z) )  0) )
  (assert (<= (+ z (* (- 1) pow2(z)) )  -1) )
  (assert (<= (+ (* (- 1) z) pow2(u1) )  0) )
  (assert (<= (+ u1 (* (- 1) pow2(u1)) )  -1) )
  
  (assert (<= (+ eee2 (* (- 1) pow2(eee2)) )  -1) )
  (assert (<= (+ (* (- 1) eee2) pow2(z) )  0) )
  (assert (<= (+ pow2(u1) (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ z (* (- 1) pow2(u1)) )  0) )
  (assert (<= (+ u1 (* (- 1) z) )  0) )
  
  (assert (<= (+ (* (- 1) pow2(eee2)) pow2(u1) )  0) )
  (assert (<= (+ eee2 (* (- 1) pow2(u1)) )  0) )
  (assert (<= (+ (* (- 1) eee2) u1 )  0) )
  (assert (<= (+ (* (- 1) u1) pow2(z) )  0) )
  (assert (<= (+ z (* (- 1) pow2(z)) )  -1) )
  
  (assert (<= (+ (* (- 1) pow2(eee2)) pow2(u1) )  0) )
  (assert (<= (+ eee2 (* (- 1) pow2(u1)) )  0) )
  (assert (<= (+ (* (- 1) eee2) pow2(z) )  0) )
  (assert (<= (+ u1 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) u1) z )  0) )
  
  (assert (<= (+ (* (- 1) pow2(eee2)) pow2(u1) )  0) )
  (assert (<= (+ (* (- 1) pow2(u1)) pow2(z) )  0) )
  (assert (<= (+ eee2 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) eee2) u1 )  0) )
  (assert (<= (+ (* (- 1) u1) z )  0) )
  
  (assert (<= (+ (* (- 1) pow2(eee2)) pow2(z) )  0) )
  (assert (<= (+ eee2 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) eee2) z )  0) )
  (assert (<= (+ (* (- 1) z) pow2(u1) )  0) )
  (assert (<= (+ u1 (* (- 1) pow2(u1)) )  -1) )
  
  (assert (<= (+ (* (- 1) pow2(eee2)) pow2(z) )  0) )
  (assert (<= (+ eee2 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) eee2) pow2(u1) )  0) )
  (assert (<= (+ z (* (- 1) pow2(u1)) )  0) )
  (assert (<= (+ u1 (* (- 1) z) )  0) )
  
  (assert (<= (+ (* (- 1) pow2(eee2)) pow2(z) )  0) )
  (assert (<= (+ pow2(u1) (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ eee2 (* (- 1) pow2(u1)) )  0) )
  (assert (<= (+ (* (- 1) eee2) z )  0) )
  (assert (<= (+ u1 (* (- 1) z) )  0) )
  
  (assert (<= (+ pow2(eee2) (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ z (* (- 1) pow2(eee2)) )  0) )
  (assert (<= (+ eee2 (* (- 1) z) )  0) )
  (assert (<= (+ (* (- 1) eee2) pow2(u1) )  0) )
  (assert (<= (+ u1 (* (- 1) pow2(u1)) )  -1) )
  
  (assert (<= (+ pow2(eee2) (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ z (* (- 1) pow2(eee2)) )  0) )
  (assert (<= (+ (* (- 1) z) pow2(u1) )  0) )
  (assert (<= (+ eee2 (* (- 1) pow2(u1)) )  0) )
  (assert (<= (+ (* (- 1) eee2) u1 )  0) )
  
  (assert (<= (+ pow2(eee2) (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) pow2(eee2)) pow2(u1) )  0) )
  (assert (<= (+ z (* (- 1) pow2(u1)) )  0) )
  (assert (<= (+ eee2 (* (- 1) z) )  0) )
  (assert (<= (+ (* (- 1) eee2) u1 )  0) )
  
  (assert (exists (y)
          (and
            (= (+ eee3 (* (- 1) u2) (* (- 1) z) )  0)
            (= (+ (* (- 1) y) (* 4 pow2(eee3)) (* 2 pow2(z)) )  0)
            (<= y  1184)
            (<= (* (- 1) u2)  0)
            (<= (* (- 1) z)  -5)
            (<= (* (- 4) pow2(u2))  -35)
            )
  )
  (assert (<= (+ eee3 (* (- 1) pow2(eee3)) )  -1) )
  (assert (<= (+ (* (- 1) eee3) pow2(u2) )  0) )
  (assert (<= (+ u2 (* (- 1) pow2(u2)) )  -1) )
  (assert (<= (+ (* (- 1) u2) pow2(z) )  0) )
  (assert (<= (+ z (* (- 1) pow2(z)) )  -1) )
  
  (assert (<= (+ eee3 (* (- 1) pow2(eee3)) )  -1) )
  (assert (<= (+ (* (- 1) eee3) pow2(u2) )  0) )
  (assert (<= (+ (* (- 1) pow2(u2)) pow2(z) )  0) )
  (assert (<= (+ u2 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) u2) z )  0) )
  
  (assert (<= (+ eee3 (* (- 1) pow2(eee3)) )  -1) )
  (assert (<= (+ (* (- 1) eee3) pow2(z) )  0) )
  (assert (<= (+ z (* (- 1) pow2(z)) )  -1) )
  (assert (<= (+ (* (- 1) z) pow2(u2) )  0) )
  (assert (<= (+ u2 (* (- 1) pow2(u2)) )  -1) )
  
  (assert (<= (+ eee3 (* (- 1) pow2(eee3)) )  -1) )
  (assert (<= (+ (* (- 1) eee3) pow2(z) )  0) )
  (assert (<= (+ pow2(u2) (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ z (* (- 1) pow2(u2)) )  0) )
  (assert (<= (+ u2 (* (- 1) z) )  0) )
  
  (assert (<= (+ (* (- 1) pow2(eee3)) pow2(u2) )  0) )
  (assert (<= (+ eee3 (* (- 1) pow2(u2)) )  0) )
  (assert (<= (+ (* (- 1) eee3) u2 )  0) )
  (assert (<= (+ (* (- 1) u2) pow2(z) )  0) )
  (assert (<= (+ z (* (- 1) pow2(z)) )  -1) )
  
  (assert (<= (+ (* (- 1) pow2(eee3)) pow2(u2) )  0) )
  (assert (<= (+ eee3 (* (- 1) pow2(u2)) )  0) )
  (assert (<= (+ (* (- 1) eee3) pow2(z) )  0) )
  (assert (<= (+ u2 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) u2) z )  0) )
  
  (assert (<= (+ (* (- 1) pow2(eee3)) pow2(u2) )  0) )
  (assert (<= (+ (* (- 1) pow2(u2)) pow2(z) )  0) )
  (assert (<= (+ eee3 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) eee3) u2 )  0) )
  (assert (<= (+ (* (- 1) u2) z )  0) )
  
  (assert (<= (+ (* (- 1) pow2(eee3)) pow2(z) )  0) )
  (assert (<= (+ eee3 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) eee3) z )  0) )
  (assert (<= (+ (* (- 1) z) pow2(u2) )  0) )
  (assert (<= (+ u2 (* (- 1) pow2(u2)) )  -1) )
  
  (assert (<= (+ (* (- 1) pow2(eee3)) pow2(z) )  0) )
  (assert (<= (+ eee3 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) eee3) pow2(u2) )  0) )
  (assert (<= (+ z (* (- 1) pow2(u2)) )  0) )
  (assert (<= (+ u2 (* (- 1) z) )  0) )
  
  (assert (<= (+ (* (- 1) pow2(eee3)) pow2(z) )  0) )
  (assert (<= (+ pow2(u2) (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ eee3 (* (- 1) pow2(u2)) )  0) )
  (assert (<= (+ (* (- 1) eee3) z )  0) )
  (assert (<= (+ u2 (* (- 1) z) )  0) )
  
  (assert (<= (+ pow2(eee3) (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ z (* (- 1) pow2(eee3)) )  0) )
  (assert (<= (+ eee3 (* (- 1) z) )  0) )
  (assert (<= (+ (* (- 1) eee3) pow2(u2) )  0) )
  (assert (<= (+ u2 (* (- 1) pow2(u2)) )  -1) )
  
  (assert (<= (+ pow2(eee3) (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ z (* (- 1) pow2(eee3)) )  0) )
  (assert (<= (+ (* (- 1) z) pow2(u2) )  0) )
  (assert (<= (+ eee3 (* (- 1) pow2(u2)) )  0) )
  (assert (<= (+ (* (- 1) eee3) u2 )  0) )
  
  (assert (<= (+ pow2(eee3) (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) pow2(eee3)) pow2(u2) )  0) )
  (assert (<= (+ z (* (- 1) pow2(u2)) )  0) )
  (assert (<= (+ eee3 (* (- 1) z) )  0) )
  (assert (<= (+ (* (- 1) eee3) u2 )  0) )
  
  (assert (exists (y)
          (and
            (= (+ eee4 (* (- 1) u3) (* (- 1) z) )  0)
            (= (+ (* (- 1) y) (* 4 pow2(eee4)) (* 3 pow2(z)) )  0)
            (<= y  1184)
            (<= (* (- 1) u3)  0)
            (<= (* (- 1) z)  -5)
            (<= (* (- 4) pow2(u3))  -34)
            )
  )
  (assert (<= (+ eee4 (* (- 1) pow2(eee4)) )  -1) )
  (assert (<= (+ (* (- 1) eee4) pow2(u3) )  0) )
  (assert (<= (+ u3 (* (- 1) pow2(u3)) )  -1) )
  (assert (<= (+ (* (- 1) u3) pow2(z) )  0) )
  (assert (<= (+ z (* (- 1) pow2(z)) )  -1) )
  
  (assert (<= (+ eee4 (* (- 1) pow2(eee4)) )  -1) )
  (assert (<= (+ (* (- 1) eee4) pow2(u3) )  0) )
  (assert (<= (+ (* (- 1) pow2(u3)) pow2(z) )  0) )
  (assert (<= (+ u3 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) u3) z )  0) )
  
  (assert (<= (+ eee4 (* (- 1) pow2(eee4)) )  -1) )
  (assert (<= (+ (* (- 1) eee4) pow2(z) )  0) )
  (assert (<= (+ z (* (- 1) pow2(z)) )  -1) )
  (assert (<= (+ (* (- 1) z) pow2(u3) )  0) )
  (assert (<= (+ u3 (* (- 1) pow2(u3)) )  -1) )
  
  (assert (<= (+ eee4 (* (- 1) pow2(eee4)) )  -1) )
  (assert (<= (+ (* (- 1) eee4) pow2(z) )  0) )
  (assert (<= (+ pow2(u3) (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ z (* (- 1) pow2(u3)) )  0) )
  (assert (<= (+ u3 (* (- 1) z) )  0) )
  
  (assert (<= (+ (* (- 1) pow2(eee4)) pow2(u3) )  0) )
  (assert (<= (+ eee4 (* (- 1) pow2(u3)) )  0) )
  (assert (<= (+ (* (- 1) eee4) u3 )  0) )
  (assert (<= (+ (* (- 1) u3) pow2(z) )  0) )
  (assert (<= (+ z (* (- 1) pow2(z)) )  -1) )
  
  (assert (<= (+ (* (- 1) pow2(eee4)) pow2(u3) )  0) )
  (assert (<= (+ eee4 (* (- 1) pow2(u3)) )  0) )
  (assert (<= (+ (* (- 1) eee4) pow2(z) )  0) )
  (assert (<= (+ u3 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) u3) z )  0) )
  
  (assert (<= (+ (* (- 1) pow2(eee4)) pow2(u3) )  0) )
  (assert (<= (+ (* (- 1) pow2(u3)) pow2(z) )  0) )
  (assert (<= (+ eee4 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) eee4) u3 )  0) )
  (assert (<= (+ (* (- 1) u3) z )  0) )
  
  (assert (<= (+ (* (- 1) pow2(eee4)) pow2(z) )  0) )
  (assert (<= (+ eee4 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) eee4) z )  0) )
  (assert (<= (+ (* (- 1) z) pow2(u3) )  0) )
  (assert (<= (+ u3 (* (- 1) pow2(u3)) )  -1) )
  
  (assert (<= (+ (* (- 1) pow2(eee4)) pow2(z) )  0) )
  (assert (<= (+ eee4 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) eee4) pow2(u3) )  0) )
  (assert (<= (+ z (* (- 1) pow2(u3)) )  0) )
  (assert (<= (+ u3 (* (- 1) z) )  0) )
  
  (assert (<= (+ (* (- 1) pow2(eee4)) pow2(z) )  0) )
  (assert (<= (+ pow2(u3) (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ eee4 (* (- 1) pow2(u3)) )  0) )
  (assert (<= (+ (* (- 1) eee4) z )  0) )
  (assert (<= (+ u3 (* (- 1) z) )  0) )
  
  (assert (<= (+ pow2(eee4) (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ z (* (- 1) pow2(eee4)) )  0) )
  (assert (<= (+ eee4 (* (- 1) z) )  0) )
  (assert (<= (+ (* (- 1) eee4) pow2(u3) )  0) )
  (assert (<= (+ u3 (* (- 1) pow2(u3)) )  -1) )
  
  (assert (<= (+ pow2(eee4) (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ z (* (- 1) pow2(eee4)) )  0) )
  (assert (<= (+ (* (- 1) z) pow2(u3) )  0) )
  (assert (<= (+ eee4 (* (- 1) pow2(u3)) )  0) )
  (assert (<= (+ (* (- 1) eee4) u3 )  0) )
  
  (assert (<= (+ pow2(eee4) (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) pow2(eee4)) pow2(u3) )  0) )
  (assert (<= (+ z (* (- 1) pow2(u3)) )  0) )
  (assert (<= (+ eee4 (* (- 1) z) )  0) )
  (assert (<= (+ (* (- 1) eee4) u3 )  0) )
  
  (assert (exists (y)
          (and
            (= (+ eee5 (* (- 1) u4) (* (- 1) z) )  0)
            (= (+ (* (- 1) y) (* 8 pow2(eee5)) (* 4 pow2(z)) )  0)
            (<= y  1184)
            (<= (* (- 1) u4)  0)
            (<= (* (- 1) z)  -5)
            (<= (* (- 8) pow2(u4))  -33)
            )
  )
  (assert (<= (+ eee5 (* (- 1) pow2(eee5)) )  -1) )
  (assert (<= (+ (* (- 1) eee5) pow2(u4) )  0) )
  (assert (<= (+ u4 (* (- 1) pow2(u4)) )  -1) )
  (assert (<= (+ (* (- 1) u4) pow2(z) )  0) )
  (assert (<= (+ z (* (- 1) pow2(z)) )  -1) )
  
  (assert (<= (+ eee5 (* (- 1) pow2(eee5)) )  -1) )
  (assert (<= (+ (* (- 1) eee5) pow2(u4) )  0) )
  (assert (<= (+ (* (- 1) pow2(u4)) pow2(z) )  0) )
  (assert (<= (+ u4 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) u4) z )  0) )
  
  (assert (<= (+ eee5 (* (- 1) pow2(eee5)) )  -1) )
  (assert (<= (+ (* (- 1) eee5) pow2(z) )  0) )
  (assert (<= (+ z (* (- 1) pow2(z)) )  -1) )
  (assert (<= (+ (* (- 1) z) pow2(u4) )  0) )
  (assert (<= (+ u4 (* (- 1) pow2(u4)) )  -1) )
  
  (assert (<= (+ eee5 (* (- 1) pow2(eee5)) )  -1) )
  (assert (<= (+ (* (- 1) eee5) pow2(z) )  0) )
  (assert (<= (+ pow2(u4) (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ z (* (- 1) pow2(u4)) )  0) )
  (assert (<= (+ u4 (* (- 1) z) )  0) )
  
  (assert (<= (+ (* (- 1) pow2(eee5)) pow2(u4) )  0) )
  (assert (<= (+ eee5 (* (- 1) pow2(u4)) )  0) )
  (assert (<= (+ (* (- 1) eee5) u4 )  0) )
  (assert (<= (+ (* (- 1) u4) pow2(z) )  0) )
  (assert (<= (+ z (* (- 1) pow2(z)) )  -1) )
  
  (assert (<= (+ (* (- 1) pow2(eee5)) pow2(u4) )  0) )
  (assert (<= (+ eee5 (* (- 1) pow2(u4)) )  0) )
  (assert (<= (+ (* (- 1) eee5) pow2(z) )  0) )
  (assert (<= (+ u4 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) u4) z )  0) )
  
  (assert (<= (+ (* (- 1) pow2(eee5)) pow2(u4) )  0) )
  (assert (<= (+ (* (- 1) pow2(u4)) pow2(z) )  0) )
  (assert (<= (+ eee5 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) eee5) u4 )  0) )
  (assert (<= (+ (* (- 1) u4) z )  0) )
  
  (assert (<= (+ (* (- 1) pow2(eee5)) pow2(z) )  0) )
  (assert (<= (+ eee5 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) eee5) z )  0) )
  (assert (<= (+ (* (- 1) z) pow2(u4) )  0) )
  (assert (<= (+ u4 (* (- 1) pow2(u4)) )  -1) )
  
  (assert (<= (+ (* (- 1) pow2(eee5)) pow2(z) )  0) )
  (assert (<= (+ eee5 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) eee5) pow2(u4) )  0) )
  (assert (<= (+ z (* (- 1) pow2(u4)) )  0) )
  (assert (<= (+ u4 (* (- 1) z) )  0) )
  
  (assert (<= (+ (* (- 1) pow2(eee5)) pow2(z) )  0) )
  (assert (<= (+ pow2(u4) (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ eee5 (* (- 1) pow2(u4)) )  0) )
  (assert (<= (+ (* (- 1) eee5) z )  0) )
  (assert (<= (+ u4 (* (- 1) z) )  0) )
  
  (assert (<= (+ pow2(eee5) (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ z (* (- 1) pow2(eee5)) )  0) )
  (assert (<= (+ eee5 (* (- 1) z) )  0) )
  (assert (<= (+ (* (- 1) eee5) pow2(u4) )  0) )
  (assert (<= (+ u4 (* (- 1) pow2(u4)) )  -1) )
  
  (assert (<= (+ pow2(eee5) (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ z (* (- 1) pow2(eee5)) )  0) )
  (assert (<= (+ (* (- 1) z) pow2(u4) )  0) )
  (assert (<= (+ eee5 (* (- 1) pow2(u4)) )  0) )
  (assert (<= (+ (* (- 1) eee5) u4 )  0) )
  
  (assert (<= (+ pow2(eee5) (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) pow2(eee5)) pow2(u4) )  0) )
  (assert (<= (+ z (* (- 1) pow2(u4)) )  0) )
  (assert (<= (+ eee5 (* (- 1) z) )  0) )
  (assert (<= (+ (* (- 1) eee5) u4 )  0) )
  
  (assert (exists (y)
          (and
            (= (+ eee6 (* (- 1) u5) (* (- 1) z) )  0)
            (= (+ (* (- 1) y) (* 8 pow2(eee6)) (* 5 pow2(z)) )  0)
            (<= y  1184)
            (<= (* (- 1) u5)  0)
            (<= (* (- 1) z)  -5)
            (<= (* (- 8) pow2(u5))  -32)
            )
  )
  (assert (<= (+ eee6 (* (- 1) pow2(eee6)) )  -1) )
  (assert (<= (+ (* (- 1) eee6) pow2(u5) )  0) )
  (assert (<= (+ u5 (* (- 1) pow2(u5)) )  -1) )
  (assert (<= (+ (* (- 1) u5) pow2(z) )  0) )
  (assert (<= (+ z (* (- 1) pow2(z)) )  -1) )
  
  (assert (<= (+ eee6 (* (- 1) pow2(eee6)) )  -1) )
  (assert (<= (+ (* (- 1) eee6) pow2(u5) )  0) )
  (assert (<= (+ (* (- 1) pow2(u5)) pow2(z) )  0) )
  (assert (<= (+ u5 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) u5) z )  0) )
  
  (assert (<= (+ eee6 (* (- 1) pow2(eee6)) )  -1) )
  (assert (<= (+ (* (- 1) eee6) pow2(z) )  0) )
  (assert (<= (+ z (* (- 1) pow2(z)) )  -1) )
  (assert (<= (+ (* (- 1) z) pow2(u5) )  0) )
  (assert (<= (+ u5 (* (- 1) pow2(u5)) )  -1) )
  
  (assert (<= (+ eee6 (* (- 1) pow2(eee6)) )  -1) )
  (assert (<= (+ (* (- 1) eee6) pow2(z) )  0) )
  (assert (<= (+ pow2(u5) (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ z (* (- 1) pow2(u5)) )  0) )
  (assert (<= (+ u5 (* (- 1) z) )  0) )
  
  (assert (<= (+ (* (- 1) pow2(eee6)) pow2(u5) )  0) )
  (assert (<= (+ eee6 (* (- 1) pow2(u5)) )  0) )
  (assert (<= (+ (* (- 1) eee6) u5 )  0) )
  (assert (<= (+ (* (- 1) u5) pow2(z) )  0) )
  (assert (<= (+ z (* (- 1) pow2(z)) )  -1) )
  
  (assert (<= (+ (* (- 1) pow2(eee6)) pow2(u5) )  0) )
  (assert (<= (+ eee6 (* (- 1) pow2(u5)) )  0) )
  (assert (<= (+ (* (- 1) eee6) pow2(z) )  0) )
  (assert (<= (+ u5 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) u5) z )  0) )
  
  (assert (<= (+ (* (- 1) pow2(eee6)) pow2(u5) )  0) )
  (assert (<= (+ (* (- 1) pow2(u5)) pow2(z) )  0) )
  (assert (<= (+ eee6 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) eee6) u5 )  0) )
  (assert (<= (+ (* (- 1) u5) z )  0) )
  
  (assert (<= (+ (* (- 1) pow2(eee6)) pow2(z) )  0) )
  (assert (<= (+ eee6 (* (- 1) pow2(z)) )  0) )
  (assert (<= (+ (* (- 1) eee6) z )  0) )
  (assert (<= (+ (* (- 1) z) pow2(u5) )  0) )
  (assert (<= (+ u5 (* (- 1) pow2(u5)) )  -1) )
  
  (assert (= (* (- 1) y)  -1184) )
  (assert (<= y  1184) )
  
  sat ; under II


