Basic LIA tests

  $ CHRO_OMIT_Z3_MODEL=1 OCAMLRUNPARAM='b=0' Chro -bound 0 -no-over ./lia.smt2
  sat (presimpl)
  unsat (presimpl)
  sat (presimpl)
  sat (presimpl)
  sat (under I)
  sat (under I)
  sat (under I)
  unsat (nia)
  sat (under I)
  sat (under I)
  sat (under I)
  unsat (nia)
  sat (under I)
  unsat (presimpl)
  unsat (presimpl)
  sat (under I)
  unsat (nia)
  sat (under I)
