Basic LIA tests

  $ CHRO_OMIT_Z3_MODEL=1 OCAMLRUNPARAM='b=0' Chro -bound 0 -no-over ./lia.smt2
  sat (presimpl int)
  unsat (presimpl int)
  sat (presimpl int)
  sat (presimpl int)
  sat (under int)
  sat (under int)
  sat (under int)
  unsat (nia)
  sat (under int)
  sat (under int)
  sat (under int)
  unsat (nia)
  sat (under int)
  unsat (presimpl int)
  unsat (presimpl int)
  sat (under int)
  unsat (nia)
  sat (under int)
