  $ cat > 1.smt2 <<-EOF
  > (set-logic QF_S)
  > (declare-const x String)
  > (declare-const y String)
  > (assert (= (str.++ "999" x) (str.++ y x)))
  > (check-sat)
  > (get-model)
  > EOF

  $ Chro 1.smt2 --dpresimpl | sed 's/[[:space:]]*$//'
  Lightweight run:
  (and
                     (= %concat1 (+ %concat4 (* %concat3 (exp 10 %concat2))))
                     (= %concat2 strlenx)
                     (= %concat3 y)
                     (= %concat4 x)
                     (= %concat5 %concat1)
                     (= %concat5 (+ %concat8 (* 999 (exp 10 %concat6))))
                     (= %concat6 strlenx)
                     (= %concat8 x)
                     (= (* (- 1) strleny) (- 3))
                     (<= 0 x)
                     (<= 0 y)
                     (<= 1 strlenx)
                     (<= 1 strleny)
                     (str.in_re.raw x)
                     (str.in_re.raw y)
                     (chrob.len x (exp 10 strlenx))
                     (chrob.len y (exp 10 strleny)))
  Lightweight run:
  (and
                     (= %concat14 %concat13)
                     (= %concat14 (+ %concat17 (* 999 (exp 10 %concat15))))
                     (= %concat15 strlenx)
                     (= %concat17 x)
                     (= strleny (+ 4 %re_len18))
                     (= (* (- 1) strleny) (- 3))
                     (<= 0 %re_len18)
                     (<= 0 strleny)
                     (<= 0 x)
                     (<= 1 strlenx)
                     (<= 1 strleny)
                     (str.in_re.raw x)
                     (chrob.len x (exp 10 strlenx))
                     str var y in unsupported concat)
  Lightweight run:
  (and
                     (= %concat21 y)
                     (= %concat28 %concat23)
                     (= strlenx (+ 1 %re_len29))
                     (= (* (- 1) strleny) (- 3))
                     (<= 0 %re_len29)
                     (<= 0 strlenx)
                     (<= 0 y)
                     (<= 1 strlenx)
                     (<= 1 strleny)
                     (str.in_re.raw y)
                     (chrob.len y (exp 10 strleny))
                     str var x in unsupported concat)
  Lightweight run:
  (and
                     (= %concat42 (+ %concat45
                                  (* %concat44 (exp 10 %concat43))))
                     (= %concat43 strlenx)
                     (= %concat44 y)
                     (= %concat45 x)
                     (= %concat46 %concat42)
                     (= %concat46 (+ %concat49 (* 999 (exp 10 %concat47))))
                     (= %concat47 strlenx)
                     (= %concat49 x)
                     (= (* (- 1) strleny) (- 3))
                     (<= 0 x)
                     (<= 0 y)
                     (<= 1 strlenx)
                     (<= 1 strleny)
                     (str.in_re.raw x)
                     (str.in_re.raw y)
                     (chrob.len x (exp 10 strlenx))
                     (chrob.len y (exp 10 strleny)))
  Lightweight run:
  (and
                     (= %concat52 y)
                     (= %concat59 %concat54)
                     (= strlenx (+ 2 %re_len60))
                     (= (* (- 1) strleny) (- 3))
                     (<= 0 %re_len60)
                     (<= 0 strlenx)
                     (<= 0 y)
                     (<= 1 strlenx)
                     (<= 1 strleny)
                     (str.in_re.raw y)
                     (chrob.len y (exp 10 strleny))
                     str var x in unsupported concat)
  Lightweight run:
  (and
                     (= %concat61 (+ %concat64
                                  (* %concat63 (exp 10 %concat62))))
                     (= %concat62 strlenx)
                     (= %concat63 y)
                     (= %concat64 x)
                     (= %concat65 %concat61)
                     (= %concat65 (+ %concat68 (* 999 (exp 10 %concat66))))
                     (= %concat66 strlenx)
                     (= %concat68 x)
                     (= (* (- 1) strleny) (- 3))
                     (<= 0 x)
                     (<= 0 y)
                     (<= 1 strlenx)
                     (<= 1 strleny)
                     (str.in_re.raw x)
                     (str.in_re.raw y)
                     (chrob.len x (exp 10 strlenx))
                     (chrob.len y (exp 10 strleny)))
  Lightweight run:
  (and
                     (= %concat71 y)
                     (= %concat78 %concat73)
                     (= strlenx (+ 3 %re_len79))
                     (= (* (- 1) strleny) (- 3))
                     (<= 0 %re_len79)
                     (<= 0 strlenx)
                     (<= 0 y)
                     (<= 1 strlenx)
                     (<= 1 strleny)
                     (str.in_re.raw y)
                     (chrob.len y (exp 10 strleny))
                     str var x in unsupported concat)
  sat (presimpl int)
  (
     (define-fun x () String
      "")   (define-fun y () String
      "999")
  )
