opam-version: "2.0"
# Fake version, actually it is 5.1.0 but at the moment (25.09.26) smtml
# requires z3 <5.0.
version: "4.16.0+z3-5.1.0"
maintainer: "weng@cs.jhu.edu"
authors: "MSR"
homepage: "https://github.com/Z3prover/z3"
bug-reports: "https://github.com/Z3prover/z3/issues"
license: "MIT"
dev-repo: "git+https://github.com/Z3prover/z3.git"
depexts: [
  ["python3-distutils"] {os-family = "debian"}
]
build: [
  [ "python3" "scripts/mk_make.py" "--staticlib" "--staticbin" "--ml" ]
  [ make "-C" "build" "-j" jobs ]
]

install: [
  [ "sed" "-i"
    "-e" "s/[^[:space:]]*dllz3ml.so[^[:space:]]*//g"
    "-e" "s| Z3 api/ml/META| z3 api/ml/META|"
    "-e" "/ocamlfind remove/ s| Z3$| z3|"
    "build/Makefile" ]
  [ "cp" "build/api/ml/libz3ml-static.a" "build/api/ml/libz3ml.a" ]
  [ make "-C" "build" "install" ]
  [ "cp" "build/api/ml/libz3ml-static.a" "/usr/lib/libz3ml-static.a" ]
  [ "cp" "build/libz3-static.a" "/usr/lib/libz3-static.a" ]
]

depends: [
  "ocaml" {>= "4.08.0"}
  "ocamlfind" {build}
  "zarith"
  "conf-gmp"
  "conf-python-3" {build}
  "conf-c++" {build}
]
x-ci-accept-failures: [
  "centos-7" "oraclelinux-7" # C compiler is too old
]
conflicts: [
  "ocaml-option-bytecode-only"
]
synopsis: "Z3 solver"
url {
  src:
    "https://github.com/Z3Prover/z3/archive/refs/tags/z3-5.1.0.tar.gz"
}
