name: Build on linux

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3

      - name: Install Smtml depedencies
        working-directory: ./vendor/smtml
        run: opam install . --deps-only --with-test --with-dev-setup

      - name: Install depedencies
        run: opam install . --deps-only --with-test

      - name: Format
        run: opam exec -- dune fmt

      - name: Build
        run: opam exec -- dune build @check @all

      - name: Tests
        run: opam exec -- dune runtest

