name: Perf different solvers on HashFunction

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:

env:
  TIMEOUT: 10s

jobs:
  hashfunction-solvers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        solver: ["Chro -bres 2 -bstates 20", "Chro -bres 1 -bstates 10", "bin/ostrich2", "bin/cvc5", "bin/z3-noodler", "bin/z3", "bin/z3str3re"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3
          dune-cache: true

      - name: Install Smtml depedencies
        working-directory: ./vendor/smtml
        run: opam install . --deps-only --with-test --with-dev-setup

      - name: Install depedencies
        run: opam install . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build @all

      - name: Run ${{ matrix.solver }} on hashfunction benchmarks
        run: |
          set +e +o pipefail;
          execut=$(echo ${{ matrix.solver }} | tr ' ' '\n' | head -n 1);
          solver=$(basename $execut);
          readarray -t flags < <(echo ${{ matrix.solver }} | tr ' ' '\n' | tail -n +2);
          base=benchmarks/chrobelias/QF_SLIA/HashFunction;
          for suite in $(find $base -type d | sort | awk '$0 !~ last "/" {print last} {last=$0} END {print last}'); do
            suitename=$(sed 's/\.//g' <<< ${suite:${#base} + 1} | sed 's/\///g');
            START_TIME=$(date +%s)
            for i in $suite"/"*.smt2; do
              echo $i;
              timeout $TIMEOUT time opam exec -- dune exec $execut --no-build -- "${flags[@]}" $i;
              if [[ $exit_status -eq 124 ]]; then
                echo "timeout";
              fi;
            done 2>&1 | tee "res_$solver_"$suitename".txt";
            END_TIME=$(date +%s)
            DURATION=$(($END_TIME - $START_TIME))
            echo "Benchmarks $suitename completed by $solver in: $DURATION seconds with $execute"
          done

      - name: Get stats
        run: |
          execut=$(echo ${{ matrix.solver }} | tr ' ' '\n' | head -n 1);
          solver=$(basename $execut);
          flags=$(echo ${{ matrix.solver }} | tr ' ' '\n' | tail -n +2 | xargs);
          base=benchmarks/chrobelias/QF_SLIA/HashFunction;
          for suite in $(find $base -type d | sort | awk '$0 !~ last "/" {print last} {last=$0} END {print last}'); do
            suitename=$(sed 's/\.//g' <<< ${suite:${#base} + 1} | sed 's/\///g');

            echo "$solver results for $suitename:";
            unsat_c=$(grep unsat res_$solver_$suitename.txt | wc -l); 
            sat_c=$(grep sat res_$solver_$suitename.txt | wc -l); 
            echo "sat     : $((sat_c - unsat_c))"; 
            echo "unsat   : $unsat_c";
            echo "timeout : $(grep timeout res_$solver_$suitename.txt | wc -l)";
            echo "total   : $(grep smt2 res_$solver_$suitename.txt | wc -l)";
          done
