name: Perf different solvers on HashFunction

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:

env:
  TIMEOUT: 10s

jobs:
  hashfunction-solvers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        solver: ["Chro -bres 2 -bstates 20", "Chro -bres 1 -bstates 10", "bin/ostrich2", "bin/cvc5", "bin/z3-noodler -memory:6144"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3
          dune-cache: true

      - name: Install Smtml depedencies
        working-directory: ./vendor/smtml
        run: opam install . --deps-only --with-test --with-dev-setup

      - name: Install depedencies
        run: opam install . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build @all

      - name: Run ${{ matrix.solver }} on hashfunction benchmarks
        run: |
          ./.github/workflows/run-benchmarks.sh "${{ matrix.solver }}" ./benchmarks/chrobelias/QF_SLIA/HashFunction $TIMEOUT

      - name: Get stats
        run: |
          ./.github/workflows/stat-benchmarks.sh "${{ matrix.solver }}" ./benchmarks/chrobelias/QF_SLIA/HashFunction
