name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "alpine:latest"
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}
    steps:
      - run: apk add alpine-sdk

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install extra dependencies
        if: startsWith(matrix.os, 'alpine')
        run: apk add bash sqlite sqlite-dev gmp gmp-dev gmp-static cmake python3 bubblewrap

      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ocaml-variants.5.3.0+options,ocaml-option-flambda,ocaml-option-static

      - run: opam --version
      - run: opam exec -- ocamlopt --version
      - run: opam switch list

      - name: Build and install static Z3
        run: |
          git clone https://github.com/Z3Prover/z3.git z3
          cp ./scripts/z3-static.opam z3/opam
          eval $(opam env)
          (cd z3 &&
           opam install .)

      - name: Install Smtml depedencies
        working-directory: ./vendor/smtml
        run: opam install . --deps-only --with-test --with-dev-setup

      - run: git config --global --add safe.directory $(pwd)

      - name: Install depedencies
        run: opam install . --deps-only --with-test -vvv

      - name: List opam packages
        run: opam list

      - name: Build
        run: opam exec -- dune build @check @all --release

      - run: mv _build/default/bin/chro.exe _build/default/bin/chro

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Chro
          path: _build/default/bin/chro

      - name: Draft release
        continue-on-error: true
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            _build/default/bin/chro
          token: "${{ secrets.GITHUB_TOKEN }}"
