name: Perf different solvers on stringfuzzregex

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:

env:
  TIMEOUT: 60s
  OPAMROOT: /home/user/.opam

jobs:
  stringfuzzregex-solvers:
    timeout-minutes: 2880
    runs-on: self-hosted
    container:
      image: we1ine/chrobelias:latest
      options: --user root --memory=8192m --cpus="1.0"
    strategy:
      fail-fast: false
      matrix:
        solver:
          #- "bin/chro.exe"
          #- "bin/ostrich2"
          #- "bin/cvc5"
          #- "bin/z3-noodler"
          - "bin/z3 -memory:6144"
          #"bin/z3str3re -memory:6144"
    steps:
      - run: opam --version
      - run: opam exec -- ocamlopt --version

      - uses: actions/checkout@v4
        with:
          submodules: true

      #- uses: ocaml/setup-ocaml@v3
      #  with:
      #    ocaml-compiler: 5.3
      #    dune-cache: true

      #- name: Install Smtml depedencies
      #  working-directory: ./vendor/smtml
      #  run: opam install . --deps-only --with-test --with-dev-setup

      #- name: Install depedencies
      #  run: opam install . --deps-only --with-test

      - name: List opam packages
        run: opam list

      - name: Build
        run: opam exec -- dune build @all

      - name: Run ${{ matrix.solver }} on stringfuzzregex benchmarks
        run: |
          ./.github/workflows/run-benchmarks.sh "${{ matrix.solver }}" benchmarks/chrobelias/QF_SLIA/stringfuzzregex/generated $TIMEOUT

      - name: Get stats
        run: |
          ./.github/workflows/stat-benchmarks.sh "${{ matrix.solver }}" benchmarks/chrobelias/QF_SLIA/stringfuzzregex/generated

      - name: Run ${{ matrix.solver }} on stringfuzzregex benchmarks
        run: |
          ./.github/workflows/run-benchmarks.sh "${{ matrix.solver }}" benchmarks/chrobelias/QF_SLIA/stringfuzzregex/transformed $TIMEOUT

      - name: Get stats
        run: |
          ./.github/workflows/stat-benchmarks.sh "${{ matrix.solver }}" benchmarks/chrobelias/QF_SLIA/stringfuzzregex/transformed
