name: Run stringfuzzregex

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:

env:
  OPAMROOT: /home/user/.opam

jobs:
  stringfuzzregex:
    if: false
    runs-on: self-hosted
    container:
      image: we1ine/chrobelias:latest
      options: --user root --memory=8192m --cpus="1.0"
    strategy:
      fail-fast: false
      matrix:
        flags: ["-q", "-q -lsb"]
    steps:
      - run: opam --version
      - run: opam exec -- ocamlopt --version

      - uses: actions/checkout@v4
        with:
          submodules: true

      #- uses: ocaml/setup-ocaml@v3
      #  with:
      #    ocaml-compiler: 5.3
      #    dune-cache: true

      #- name: Install Smtml depedencies
      #  working-directory: ./vendor/smtml
      #  run: opam install . --deps-only --with-test --with-dev-setup

      #- name: Install depedencies
      #  run: opam install . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build

      - name: Run stringfuzzregex and measure time
        run: |
          set +e;
          START_TIME=$(date +%s)
          for i in ./benchmarks/chrobelias/QF_SLIA/stringfuzzregex/*.smt2; do
            echo $i;
            timeout 10s _build/default/bin/chro.exe ${{ matrix.flags }} $i;
          done 2>&1 | tee res.txt;
          END_TIME=$(date +%s)
          DURATION=$(($END_TIME - $START_TIME))
          echo "Benchmarks completed in: $DURATION seconds with ${{ matrix.flags }}"

      - name: Get stats
        run: |
          echo "StringFuzzRegex with ${{ matrix.flags }} flags";
          echo "errors  : $(grep error res.txt | wc -l)";
          echo "warnings: $(grep warn res.txt | wc -l)";
          echo "timeouts: $(grep timeout res.txt | wc -l)";
          echo "unknown : $(grep unknown res.txt | wc -l)";
          echo "total   : $(grep chrobelias res.txt | wc -l)";
