name: Perf different solvers on StrRElnc

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

env:
  TIMEOUT: 30s

jobs:
  strrelnc-solvers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        solver: ["Chro", "bin/ostrich2", "bin/cvc5", "bin/z3-noodler", "bin/z3 -memory:6144", "bin/z3str3re -memory:6144"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3
          dune-cache: true

      - name: Install Smtml depedencies
        working-directory: ./vendor/smtml
        run: opam install . --deps-only --with-test --with-dev-setup

      - name: Install depedencies
        run: opam install . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build @all

      - name: Run ${{ matrix.solver }} on strrelnc benchmarks
        run: |
          ./.github/workflows/run-benchmarks.sh ${{ matrix.solver }} ./benchmarks/chrobelias/QF_SLIA/StrRElnc/RElnc $TIMEOUT

      - name: Get stats
        run: |
          ./.github/workflows/stat-benchmarks.sh ${{ matrix.solver }} ./benchmarks/chrobelias/QF_SLIA/StrRElnc/RElnc
